import React from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { FiMapPin, FiCalendar, FiDollarSign, FiZap } from "react-icons/fi";
import { motion } from "framer-motion";

const features = [
  {
    icon: FiZap,
    title: "AI-Powered Itineraries",
    desc: "Get personalized day-by-day travel plans generated by advanced AI in seconds.",
    color: "text-glow-cyan",
  },
  {
    icon: FiMapPin,
    title: "Smart Destinations",
    desc: "Discover places to visit, local restaurants, and hidden gems at your destination.",
    color: "text-glow-purple",
  },
  {
    icon: FiDollarSign,
    title: "Budget Aware",
    desc: "Plans tailored to your budget — whether backpacking or luxury traveling.",
    color: "text-glow-pink",
  },
  {
    icon: FiCalendar,
    title: "Flexible Planning",
    desc: "Plan trips from 1 to 30 days for solo, couple, family, or friend adventures.",
    color: "text-yellow-400",
  },
];

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.12, duration: 0.5 },
  }),
};

export default function Home() {
  const { user } = useAuth();

  return (
    <div className="min-h-screen pt-16">
      {/* Hero */}
      <section className="relative overflow-hidden">
        {/* Background blobs */}
        <div className="absolute -top-40 -left-40 w-96 h-96 bg-glow-cyan/10 rounded-full blur-3xl" />
        <div className="absolute top-20 right-0 w-80 h-80 bg-glow-purple/10 rounded-full blur-3xl" />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 sm:py-36 text-center relative z-10">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-4xl sm:text-6xl lg:text-7xl font-extrabold leading-tight"
          >
            Plan Your Dream Trip
            <br />
            <span className="gradient-text">with AI Intelligence</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.6 }}
            className="mt-6 text-lg sm:text-xl text-dark-300 max-w-2xl mx-auto"
          >
            Enter your destination, budget, and travel style. Our AI creates a
            complete day-wise itinerary with places, costs, hotel tips, and more.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.4 }}
            className="mt-10 flex flex-col sm:flex-row gap-4 justify-center"
          >
            <Link
              to={user ? "/create" : "/signup"}
              className="inline-flex items-center justify-center gap-2 bg-gradient-to-r from-glow-cyan via-accent-500 to-glow-purple text-white font-semibold px-8 py-3.5 rounded-xl text-lg hover:opacity-90 transition shadow-lg shadow-accent-500/25"
            >
              <FiZap className="w-5 h-5" />
              Start Planning
            </Link>
            {!user && (
              <Link
                to="/login"
                className="inline-flex items-center justify-center border border-white/10 text-dark-200 font-medium px-8 py-3.5 rounded-xl text-lg hover:bg-white/5 transition"
              >
                Login
              </Link>
            )}
          </motion.div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <h2 className="text-3xl font-bold text-center mb-14">
          Why <span className="gradient-text">TripAI</span>?
        </h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeUp}
              className="glass rounded-2xl p-6 hover:border-white/10 transition group"
            >
              <f.icon className={`w-8 h-8 ${f.color} mb-4`} />
              <h3 className="text-lg font-semibold text-white mb-2">
                {f.title}
              </h3>
              <p className="text-sm text-dark-400 leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 py-8 text-center text-dark-500 text-sm">
        &copy; {new Date().getFullYear()} TripAI. Built with React, Node.js &amp; OpenAI.
      </footer>
    </div>
  );
}
